# Generated by Django 3.1.7 on 2021-03-20 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Lists')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=250, verbose_name='Tasks')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('due', models.DateField(default=django.utils.timezone.now, verbose_name='Due to')),
                ('owner', models.CharField(default='admin', max_length=300, verbose_name='Owner')),
                ('mark', models.BooleanField(default=False, verbose_name='Mark')),
                ('lists', models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.todo')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
