# Generated by Django 3.1.7 on 2021-03-20 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookJournalBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookjournalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.bookjournalbase')),
                ('num_pages', models.IntegerField()),
                ('genre', models.CharField(max_length=80)),
            ],
            bases=('main.bookjournalbase',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('bookjournalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.bookjournalbase')),
                ('type', models.SmallIntegerField(choices=[(1, 'bullet'), (2, 'food'), (3, 'travel'), (4, 'sport')], default=1)),
                ('publisher', models.CharField(max_length=200)),
            ],
            bases=('main.bookjournalbase',),
        ),
    ]
